BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
                on_press: app.handle_increment(+1)
            Button:
                text: 'Down'
                on_press: app.handle_increment(-1)
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Convert miles to km'
        Label:
            color: (1, 1, 0, 1)
            id: output_number